title: "Geolexica"

email: open.source@ribose.com

description: >-
  Welcome to Geolexica, the authoritative glossary for geographic
  information technology from ISO/TC 211.

baseurl: ""
url: "https://geolexica.com"

social:
  links:
    - url: https://twitter.com/ISOTC211
    - url: https://github.com/ISO-TC211
    - url: https://www.facebook.com/groups/236669159734679/
    - url: https://www.linkedin.com/groups/4222374

# Layouts and pages can include nav_items array referring to link IDs in frontmatter
nav:
  home:
    url: /
    title: Home
  about:
    url: /about
    title: About
  concepts:
    url: /concepts
    title: Concepts

footer_nav:
  - url: https://committee.iso.org/home/tc211
    title: ISO/TC 211

powered_by:
  url: https://open.ribose.com
  title: Ribose
  logo_path: /assets/logo-ribose.svg

theme: jekyll-theme-isotc211

sass:
  style: compressed

collections:
  pages:
    output: true
    permalink: /:path/
  concepts:
    output: true
    permalink: /:collection/:name/
  concepts_json:
    output: true
    output_ext: .json
    permalink: /api/concepts/:name.json

defaults:
  - scope:
      path: ""
      type: "concepts"
    values:
      layout: concept
  - scope:
      path: ""
      type: "concepts_json"
    values:
      layout: concept.json
      permalink: /api/concepts/:name.json

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - deploy.sh
  - "*.xlsx"
  - "*.yaml"
  - concepts_data
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
