# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Geolexica"
email: open.source@ribose.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to Geolexica, the authoritative glossary for geographic
  information technology from ISO/TC 211.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.geolexica.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ISOTC211
github_username:  ISO-TC211

# TODO add these
# https://www.iso.org/committee/54904.html#meetings
# https://www.facebook.com/groups/236669159734679/
# https://www.linkedin.com/groups/4222374


# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed

sass:
  style: compressed

collections:
  pages:
    output: true
    permalink: /:path/
  concepts:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: "concept"
    values:
      layout: concept

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - deploy.sh
  - "*.xlsx"
  - "*.yaml"
  - concepts_data
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
